# Generated by Django 3.0.5 on 2020-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SE', '- Please Select Provider...'), ('BI', 'Blockchain Info')], default='SE', max_length=2)),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled?', verbose_name='Is enabled?')),
                ('name', models.CharField(default='Provider XYZ', help_text='A friendly name (e.g. Bitcoin Average APIv2).', max_length=128, verbose_name='name')),
                ('url', models.CharField(blank=True, help_text='URL.', max_length=1000, null=True, verbose_name='url')),
                ('username', models.CharField(blank=True, help_text='Username.', max_length=256, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, help_text='Password.', max_length=256, null=True, verbose_name='password')),
                ('token', models.CharField(blank=True, help_text='API Token.', max_length=256, null=True, verbose_name='token')),
                ('config', models.CharField(blank=True, help_text='Dictionary (JSON encoded) with arbitrary configuration settings.', max_length=1000, null=True, verbose_name='config')),
            ],
            options={
                'verbose_name': 'Provider Setting',
                'verbose_name_plural': 'Provider Settings',
            },
        ),
    ]
